name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_pika:
    runs-on: ubuntu-20.04 
    # Docker Hub image that `container-job` executes in
    container:
      image: osrf/ros:noetic-desktop-full
    defaults:
      run:
        shell: bash
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      rabbitmq:
        # Docker Hub image
        image: rabbitmq:3
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip
          sudo pip3 install pika==0.13 aio-pika
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        env:
          RABBITMQ_HOST: rabbitmq
        run: |
          ls
          pwd
          python3 test_rabbitmq.py
          python3 test_aio_pika.py
